//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPERIMENT14_WEBSERVICE.MyMartService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://electronicmart.org/", ConfigurationName="MyMartService.MartServiceSoap")]
    public interface MartServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://electronicmart.org/GetTax", ReplyAction="*")]
        double GetTax(double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://electronicmart.org/GetTax", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetTaxAsync(double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://electronicmart.org/GetTotal", ReplyAction="*")]
        double GetTotal(double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://electronicmart.org/GetTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetTotalAsync(double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MartServiceSoapChannel : EXPERIMENT14_WEBSERVICE.MyMartService.MartServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MartServiceSoapClient : System.ServiceModel.ClientBase<EXPERIMENT14_WEBSERVICE.MyMartService.MartServiceSoap>, EXPERIMENT14_WEBSERVICE.MyMartService.MartServiceSoap {
        
        public MartServiceSoapClient() {
        }
        
        public MartServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MartServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MartServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MartServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetTax(double amount) {
            return base.Channel.GetTax(amount);
        }
        
        public System.Threading.Tasks.Task<double> GetTaxAsync(double amount) {
            return base.Channel.GetTaxAsync(amount);
        }
        
        public double GetTotal(double amount) {
            return base.Channel.GetTotal(amount);
        }
        
        public System.Threading.Tasks.Task<double> GetTotalAsync(double amount) {
            return base.Channel.GetTotalAsync(amount);
        }
    }
}
